export type AnimalCutEntry = {
  slug: string;
  name: string;
  nameAr: string;
  image: string; // Cloudinary public ID
  defaultWeight: string;
  price: number | null;
  subtitle: string;
  subtitleAr: string;
  productSlug?: string;
};

export type AnimalCutsMap = Record<string, AnimalCutEntry[]>;

const IMG = {
  // Beef (Premium local generated assets)
  ribeye: 'products/beef/ribeye_steak',
  tenderloin: 'products/beef/beef_tenderloin',
  tbone: 'products/beef/t_bone_steak',
  tomahawk: 'products/beef/tomahawk_steak',
  mincedBeef: 'products/beef/minced_beef',
  sirloinSteak: 'products/beef/sirloin_steak',
  beefLiver: 'products/beef/beef_liver',
  beefBrisket: 'products/beef/beef_brisket',
  beefShortRibs: 'products/beef/beef_ribs',
  beefShank: 'products/beef/beef_shank',

  // Buffalo (Unique local placeholders)
  buffaloSteak: 'products/buffalo/buffalo_steak',
  buffaloMinced: 'products/buffalo/buffalo_minced',
  buffaloLiver: 'products/buffalo/buffalo_liver',
  buffaloShank: 'products/buffalo/buffalo_shank',
  buffaloRibs: 'products/buffalo/buffalo_ribs',
  buffaloStew: 'products/buffalo/buffalo_stew',

  // Lamb (Premium local generated assets & placeholders)
  lambChops: 'products/lamb/lamb_chops',
  legOfLamb: 'products/lamb/leg_of_lamb',
  lambShoulder: 'products/lamb/lamb_shoulder',
  lambRibs: 'products/lamb/lamb_ribs',
  mincedLamb: 'products/lamb/minced_lamb',
  lambShank: 'products/lamb/lamb_shank',
  lambNeck: 'products/lamb/lamb_neck',

  // Goat (Unique local placeholders)
  goatMeat: 'products/goat/goat_meat',
  goatChops: 'products/goat/goat_chops',
  goatShoulder: 'products/goat/goat_shoulder',
  goatLeg: 'products/goat/goat_leg',
  goatShank: 'products/goat/goat_shank',
  goatMinced: 'products/goat/goat_minced',

  // Veal (Premium local generated assets & placeholders)
  vealCutlets: 'products/veal/veal_steak',
  vealChops: 'products/veal/veal_chops',
  vealShoulder: 'products/veal/veal_shoulder',
  vealMinced: 'products/veal/veal_minced',
  vealLiver: 'products/veal/veal_liver',
  vealShank: 'products/veal/veal_shank',
  vealStew: 'products/veal/veal_stew',
} as const;

export const ANIMAL_CUTS: AnimalCutsMap = {
  beef: [
    {
      slug: 'ribeye',
      name: 'Ribeye Steak',
      nameAr: 'ريب آي ستيك',
      image: IMG.ribeye,
      defaultWeight: '1kg',
      price: 480,
      subtitle: 'Well-marbled and tender, perfect for grilling or pan-searing.',
      subtitleAr: 'قطعة غنية بالتشحيم وطرية، مثالية للشوي أو التشويح في الطاسة.',
      productSlug: 'dry-aged-ribeye-steak',
    },
    {
      slug: 'tenderloin',
      name: 'Beef Tenderloin',
      nameAr: 'تندرلوين بقري',
      image: IMG.tenderloin,
      defaultWeight: '1kg',
      price: 620,
      subtitle: 'A lean and extra-tender cut, ideal for medallions and premium steaks.',
      subtitleAr: 'قطعة قليلة الدهن وشديدة الطراوة، مثالية لشرائح الستيك الفاخرة.',
      productSlug: 'beef-tenderloin',
    },
    {
      slug: 't-bone',
      name: 'T-Bone Steak',
      nameAr: 'تي بون ستيك',
      image: IMG.tbone,
      defaultWeight: '1kg',
      price: 550,
      subtitle: 'Combining tenderloin and strip steak on the bone for the best of both worlds.',
      subtitleAr: 'يجمع بين لحم الفيليه والانتركوت على العظم للاستمتاع بأفضل قطعتين.',
      productSlug: 't-bone-steak',
    },
    {
      slug: 'tomahawk',
      name: 'Tomahawk Steak',
      nameAr: 'توماهوك ستيك',
      image: IMG.tomahawk,
      defaultWeight: '1.5kg',
      price: 750,
      subtitle: 'A thick-cut ribeye on an extra-long, french-trimmed bone for a striking presentation.',
      subtitleAr: 'قطعة ريب آي سميكة بعظم طويل منسق بعناية لمظهر مبهر وجذاب.',
      productSlug: 'tomahawk-steak',
    },
    {
      slug: 'minced-beef',
      name: 'Minced Beef',
      nameAr: 'لحم بقري مفروم',
      image: IMG.mincedBeef,
      defaultWeight: '1kg',
      price: 280,
      subtitle: 'Freshly minced daily, great for kofta, burgers, and pasta sauces.',
      subtitleAr: 'مفروم طازج يوميًا، مناسب للكفتة والبرجر وصوصات المكرونة.',
      productSlug: 'premium-minced-beef',
    },
    {
      slug: 'steak',
      name: 'Beef Steak',
      nameAr: 'ستيك بقري',
      image: IMG.sirloinSteak,
      defaultWeight: '1kg',
      price: 420,
      subtitle: 'Thick steak cut for grilling, pan-frying, or classic steak meals.',
      subtitleAr: 'قطعة ستيك سميكة مناسبة للشوي أو الطهي في الطاسة.',
      productSlug: 'prime-sirloin-steak',
    },
    {
      slug: 'liver',
      name: 'Beef Liver',
      nameAr: 'كبدة بقري',
      image: IMG.beefLiver,
      defaultWeight: '1kg',
      price: 180,
      subtitle: 'Fresh and tender liver, perfect for quick traditional recipes.',
      subtitleAr: 'كبدة طازجة وطرية، مناسبة للوصفات السريعة والمذاق الشرقي.',
      productSlug: 'beef-liver',
    },
    {
      slug: 'brisket',
      name: 'Beef Brisket',
      nameAr: 'بريسكت بقري',
      image: IMG.beefBrisket,
      defaultWeight: '1kg',
      price: 350,
      subtitle: 'A rich cut best suited for slow cooking, roasting, and BBQ.',
      subtitleAr: 'قطعة غنية بالنكهة، مناسبة للطهي البطيء والشوي والباربكيو.',
      productSlug: 'beef-brisket',
    },
    {
      slug: 'short-ribs',
      name: 'Beef Short Ribs',
      nameAr: 'شورت ريبس بقري',
      image: IMG.beefShortRibs,
      defaultWeight: '1kg',
      price: 300,
      subtitle: 'Bone-in beef ribs with deep flavour, ideal for slow-cooked dishes.',
      subtitleAr: 'ضلوع بقري بالعظم بنكهة قوية، مثالية للوصفات المطهية ببطء.',
      productSlug: 'beef-short-ribs',
    },
    {
      slug: 'beef-shanks',
      name: 'Beef Shank',
      nameAr: 'موزة بقري',
      image: IMG.beefShank,
      defaultWeight: '1kg',
      price: 310,
      subtitle: 'Rich in marrow and collagen, perfect for slow-braising and tagines.',
      subtitleAr: 'غنية بالنخاع والكولاجين، مثالية للطهي البطيء والطواجن.',
      productSlug: 'beef-shanks',
    },
  ],

  buffalo: [
    {
      slug: 'buffalo-steaks',
      name: 'Buffalo Steak',
      nameAr: 'ستيك جاموسي',
      image: IMG.buffaloSteak,
      defaultWeight: '1kg',
      price: 380,
      subtitle: 'Lean steak with a rich flavour, great for grilling and pan-cooking.',
      subtitleAr: 'ستيك قليل الدهن بنكهة قوية، مناسب للشوي والطهي في الطاسة.',
      productSlug: 'buffalo-steaks',
    },
    {
      slug: 'buffalo-minced',
      name: 'Minced Buffalo',
      nameAr: 'لحم جاموسي مفروم',
      image: IMG.buffaloMinced,
      defaultWeight: '1kg',
      price: 220,
      subtitle: 'Lean minced meat, a practical choice for kofta and homemade burgers.',
      subtitleAr: 'لحم مفروم قليل الدهن، مناسب للكفتة والبرجر البيتي.',
      productSlug: 'minced-buffalo',
    },
    {
      slug: 'buffalo-liver',
      name: 'Buffalo Liver',
      nameAr: 'كبدة جاموسي',
      image: IMG.buffaloLiver,
      defaultWeight: '1kg',
      price: 160,
      subtitle: 'Fresh liver with a rich local taste, ideal for quick cooking.',
      subtitleAr: 'كبدة طازجة بطعم غني، مناسبة للوصفات السريعة.',
      productSlug: 'buffalo-liver',
    },
    {
      slug: 'buffalo-shanks',
      name: 'Buffalo Shank',
      nameAr: 'موزة جاموسي',
      image: IMG.buffaloShank,
      defaultWeight: '1kg',
      price: 250,
      subtitle: 'A hearty cut with marrow, perfect for soups and slow braises.',
      subtitleAr: 'قطعة غنية بالمخ، مثالية للشوربة والطهي البطيء.',
      productSlug: 'buffalo-shank',
    },
    {
      slug: 'buffalo-ribs',
      name: 'Buffalo Ribs',
      nameAr: 'ريش جاموسي',
      image: IMG.buffaloRibs,
      defaultWeight: '1kg',
      price: 290,
      subtitle: 'Fleshy and robust ribs, excellent for slow roasting or barbecue.',
      subtitleAr: 'ضلوع غنية باللحم بنكهة مميزة، ممتازة للشوي والطهي البطيء.',
      productSlug: 'buffalo-ribs',
    },
    {
      slug: 'buffalo-stew',
      name: 'Buffalo Stew Cuts',
      nameAr: 'لحم جاموسي مكعبات',
      image: IMG.buffaloStew,
      defaultWeight: '1kg',
      price: 260,
      subtitle: 'Premium lean chunks ideal for stews and traditional vegetable tagines.',
      subtitleAr: 'مكعبات لحم أحمر ممتازة، مثالية لليخني والطواجن البلدي بالخضار.',
      productSlug: 'buffalo-stew',
    },
  ],

  lamb: [
    {
      slug: 'lamb-chops',
      name: 'Lamb Chops',
      nameAr: 'ريش ضاني',
      image: IMG.lambChops,
      defaultWeight: '1kg',
      price: 450,
      subtitle: 'Tender and juicy chops, perfect for grilling and special meals.',
      subtitleAr: 'ريش طرية وعصيرية، مثالية للشوي والوجبات المميزة.',
      productSlug: 'premium-lamb-chops',
    },
    {
      slug: 'leg',
      name: 'Leg of Lamb',
      nameAr: 'فخذة ضاني',
      image: IMG.legOfLamb,
      defaultWeight: '1kg',
      price: 380,
      subtitle: 'A classic roasting cut, ideal for family meals and gatherings.',
      subtitleAr: 'قطعة مثالية للشوي، مناسبة للعزومات والوجبات العائلية.',
      productSlug: 'whole-leg-of-lamb',
    },
    {
      slug: 'shoulder',
      name: 'Lamb Shoulder',
      nameAr: 'كتف ضاني',
      image: IMG.lambShoulder,
      defaultWeight: '1kg',
      price: 350,
      subtitle: 'A flavourful cut that works beautifully in slow-cooked dishes.',
      subtitleAr: 'قطعة غنية بالنكهة ومناسبة جدًا للطهي البطيء.',
      productSlug: 'lamb-shoulder',
    },
    {
      slug: 'lamb-ribs',
      name: 'Lamb Ribs',
      nameAr: 'ضلوع ضاني',
      image: IMG.lambRibs,
      defaultWeight: '1kg',
      price: 320,
      subtitle: 'Tender ribs with rich flavour, especially good for the grill.',
      subtitleAr: 'ضلوع طرية وغنية بالنكهة، ممتازة للشوي.',
      productSlug: 'lamb-ribs',
    },
    {
      slug: 'minced-lamb',
      name: 'Minced Lamb',
      nameAr: 'لحم ضاني مفروم',
      image: IMG.mincedLamb,
      defaultWeight: '1kg',
      price: 300,
      subtitle: 'Rich minced lamb, ideal for kofta, hawawshi, and stuffed recipes.',
      subtitleAr: 'لحم ضاني مفروم غني، مناسب للكفتة والحواوشي والمحاشي.',
      productSlug: 'minced-lamb',
    },
    {
      slug: 'lamb-shanks',
      name: 'Lamb Shank',
      nameAr: 'موزة ضاني',
      image: IMG.lambShank,
      defaultWeight: '1kg',
      price: 420,
      subtitle: 'Melt-in-your-mouth tender cut on the bone, perfect for slow-cooked tagines and kabsa.',
      subtitleAr: 'قطعة لحم تذوب في الفم بالعظم، مثالية للطهي البطيء والطواجن والكبسة.',
      productSlug: 'lamb-shank',
    },
    {
      slug: 'lamb-neck',
      name: 'Lamb Neck',
      nameAr: 'رقبة ضاني',
      image: IMG.lambNeck,
      defaultWeight: '1kg',
      price: 360,
      subtitle: 'Exceptionally rich and gelatinous cut, ideal for soups and slow-braising.',
      subtitleAr: 'قطعة غنية بالجيلاتين والنكهة، مثالية للشوربة الفاخرة والطهي البطيء.',
      productSlug: 'lamb-neck',
    },
  ],

  goat: [
    {
      slug: 'goat-curry-cuts',
      name: 'Goat Meat Cuts',
      nameAr: 'لحم ماعز للطبخ',
      image: IMG.goatMeat,
      defaultWeight: '1kg',
      price: 300,
      subtitle: 'Bone-in cuts ideal for slow cooking, soups, and stews.',
      subtitleAr: 'قطع بالعظم مناسبة للطهي البطيء والشوربات واليخني.',
      productSlug: 'goat-meat-cuts',
    },
    {
      slug: 'goat-chops',
      name: 'Goat Chops',
      nameAr: 'ريش ماعز',
      image: IMG.goatChops,
      defaultWeight: '1kg',
      price: 350,
      subtitle: 'Lean chops with a bold flavour, great for grilling.',
      subtitleAr: 'ريش قليلة الدهن بنكهة قوية، مناسبة للشوي.',
      productSlug: 'goat-chops',
    },
    {
      slug: 'goat-shoulder',
      name: 'Goat Shoulder',
      nameAr: 'كتف ماعز',
      image: IMG.goatShoulder,
      defaultWeight: '1kg',
      price: 280,
      subtitle: 'Tender shoulder cut, best for braising and slow cooking.',
      subtitleAr: 'كتف طري، مناسب للطهي البطيء والتسوية على نار هادئة.',
      productSlug: 'goat-shoulder',
    },
    {
      slug: 'goat-leg',
      name: 'Goat Leg',
      nameAr: 'فخذة ماعز',
      image: IMG.goatLeg,
      defaultWeight: '1kg',
      price: 320,
      subtitle: 'A lean roasting cut with full flavour and firm texture.',
      subtitleAr: 'قطعة قليلة الدهن، مناسبة للشوي وبنكهة مميزة.',
      productSlug: 'goat-leg',
    },
    {
      slug: 'goat-shanks',
      name: 'Goat Shank',
      nameAr: 'موزة ماعز',
      image: IMG.goatShank,
      defaultWeight: '1kg',
      price: 310,
      subtitle: 'Flavorful, slow-braising cut rich in collagen.',
      subtitleAr: 'قطعة لحم غنية بالنكهة ومثالية للتسوية البطيئة على نار هادئة.',
      productSlug: 'goat-shanks',
    },
    {
      slug: 'goat-minced',
      name: 'Minced Goat',
      nameAr: 'لحم ماعز مفروم',
      image: IMG.goatMinced,
      defaultWeight: '1kg',
      price: 320,
      subtitle: 'Lean minced goat meat, great for traditional kofta and pies.',
      subtitleAr: 'مفروم ماعز قليل الدهن، ممتاز للكفتة التقليدية والفطائر.',
      productSlug: 'goat-minced',
    },
  ],

  veal: [
    {
      slug: 'veal-cutlets',
      name: 'Veal Cutlets',
      nameAr: 'كوتليتة عجل',
      image: IMG.vealCutlets,
      defaultWeight: '1kg',
      price: 450,
      subtitle: 'Tender veal cutlets with a mild flavour and soft texture.',
      subtitleAr: 'كوتليتة عجل طرية بنكهة خفيفة وقوام ناعم.',
      productSlug: 'veal-cutlets',
    },
    {
      slug: 'veal-chops',
      name: 'Veal Chops',
      nameAr: 'ريش عجل',
      image: IMG.vealChops,
      defaultWeight: '1kg',
      price: 400,
      subtitle: 'Tender chops with a delicate flavour, ideal for grilling.',
      subtitleAr: 'ريش طرية بنكهة خفيفة، مناسبة للشوي.',
      productSlug: 'veal-chops',
    },
    {
      slug: 'veal-shoulder',
      name: 'Veal Shoulder',
      nameAr: 'كتف عجل',
      image: IMG.vealShoulder,
      defaultWeight: '1kg',
      price: 320,
      subtitle: 'A versatile cut for roasting, stews, and everyday cooking.',
      subtitleAr: 'قطعة متعددة الاستخدامات، مناسبة للشوي واليخني والطبخ اليومي.',
      productSlug: 'veal-shoulder',
    },
    {
      slug: 'veal-minced',
      name: 'Minced Veal',
      nameAr: 'لحم عجل مفروم',
      image: IMG.vealMinced,
      defaultWeight: '1kg',
      price: 280,
      subtitle: 'Light minced veal for burgers, kofta, and home cooking.',
      subtitleAr: 'لحم عجل مفروم خفيف، مناسب للبرجر والكفتة والطبخ المنزلي.',
      productSlug: 'veal-minced',
    },
    {
      slug: 'veal-liver',
      name: 'Veal Liver',
      nameAr: 'كبدة عجل',
      image: IMG.vealLiver,
      defaultWeight: '1kg',
      price: 200,
      subtitle: 'Tender liver with a smooth flavour, great for quick meals.',
      subtitleAr: 'كبدة طرية بنكهة خفيفة، مناسبة للوجبات السريعة.',
      productSlug: 'veal-liver',
    },
    {
      slug: 'veal-shanks',
      name: 'Veal Shank',
      nameAr: 'موزة عجل',
      image: IMG.vealShank,
      defaultWeight: '1kg',
      price: 380,
      subtitle: 'Tender and rich in gelatin, perfect for Osso Buco and rich stews.',
      subtitleAr: 'طرية للغاية وغنية بالجيلاتين، مثالية لطبق الأوسوبوكو واليخني الغني.',
      productSlug: 'veal-shanks',
    },
    {
      slug: 'veal-stew',
      name: 'Veal Stew Cuts',
      nameAr: 'لحم عجل مكعبات',
      image: IMG.vealStew,
      defaultWeight: '1kg',
      price: 340,
      subtitle: 'Succulent, boneless cubes, perfect for light tagines and quick cooking.',
      subtitleAr: 'مكعبات طرية خالية من العظم، مثالية للطواجن الخفيفة والطبخ السريع.',
      productSlug: 'veal-stew',
    },
  ],
} as const;